# 是否启用队伍系统
enabled: true

# 默认队伍人数上限
default-team-size: 8

# 每个队伍的人数上限可以在此处配置
team-size:
  # 队伍名1: 人数上限
  "teamname1": 10
  # 队伍名2: 人数上限
  "teamname2": 5

# 队伍的配置
teams:
  # 示例队伍配置
  TeamName:
    leader: "player-uuid"
    members:
      - "player-uuid"
      - "player-uuid"
    viceLeaders:
      - "player-uuid"
