name: ZDteam
version: 1.2.1
main: com.example.zdteam.ZDteam
api-version: 1.16
commands:
  zd:
    description: "队伍管理指令"
    usage: "/<command> <子命令> [参数]"
    aliases:
      - team
    permission: zdteam.use
    permission-message: "你没有权限使用此指令！"
permissions:
  zdteam.use:
    description: "允许使用所有队伍相关指令"
    default: true
  zdteam.reload:
    description: "允许重载插件配置"
    default: op
  zdteam.create:
    description: "允许创建队伍"
    default: true
  zdteam.invite:
    description: "允许邀请玩家加入队伍"
    default: true
  zdteam.disband:
    description: "允许解散队伍"
    default: true
  zdteam.kick:
    description: "允许踢出队伍成员"
    default: true
  zdteam.promote:
    description: "允许提升玩家为副队长"
    default: true
  zdteam.demote:
    description: "允许撤销副队长职务"
    default: true
  zdteam.transfer:
    description: "允许转让队长职位"
    default: true
  zdteam.friendlyfire:
    description: "允许开启或关闭队伍友伤"
    default: true
